# Store Type creation script using kfutil
# Generated by Doctool

Write-Host "Creating store type: AzureAppGw"
kfutil store-types create AzureAppGw

Write-Host "Creating store type: AppGwBin"
kfutil store-types create AppGwBin

