#!/bin/bash
# Store Type creation script using curl
# Generated by Doctool

set -e

# Configuration - set these variables before running
KEYFACTOR_HOSTNAME="${KEYFACTOR_HOSTNAME}"
KEYFACTOR_API_PATH="${KEYFACTOR_API_PATH:-KeyfactorAPI}"
KEYFACTOR_AUTH_TOKEN="${KEYFACTOR_AUTH_TOKEN}"

echo "Creating store type: AzureAppGw"
curl -s -X POST "https://${KEYFACTOR_HOSTNAME}/${KEYFACTOR_API_PATH}/CertificateStoreTypes" \
  -H "Authorization: Bearer ${KEYFACTOR_AUTH_TOKEN}" \
  -H "Content-Type: application/json" \
  -H "x-keyfactor-requested-with: APIClient" \
  -d '{
  "Name": "Azure Application Gateway Certificate",
  "ShortName": "AzureAppGw",
  "Capability": "AzureAppGw",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Remove": true,
    "Enrollment": false,
    "Discovery": true,
    "Inventory": true
  },
  "Properties": [
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "Description": "Application ID of the service principal, representing the identity used for managing the Application Gateway.",
      "Required": false
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Type": "Secret",
      "Description": "A Client Secret that the extension will use to authenticate with the Azure Resource Management API for managing Application Gateway certificates, OR the password that encrypts the private key in ClientCertificate",
      "Required": false
    },
    {
      "Name": "ClientCertificate",
      "DisplayName": "Client Certificate",
      "Type": "Secret",
      "Description": "The client certificate used to authenticate with Azure Resource Management API for managing Application Gateway certificates. See the [requirements](#client-certificate-or-client-secret) for more information.",
      "Required": false
    },
    {
      "Name": "AzureCloud",
      "DisplayName": "Azure Global Cloud Authority Host",
      "Type": "MultipleChoice",
      "DefaultValue": "public,china,government",
      "Description": "Specifies the Azure Cloud instance used by the organization.",
      "Required": false
    },
    {
      "Name": "ServerUseSsl",
      "DisplayName": "Use SSL",
      "Type": "Bool",
      "DefaultValue": "true",
      "Description": "Specifies whether SSL should be used for communication with the server. Set to 'true' to enable SSL, and 'false' to disable it.",
      "Required": true
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "PrivateKeyAllowed": "Required",
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required"
}'

echo "Creating store type: AppGwBin"
curl -s -X POST "https://${KEYFACTOR_HOSTNAME}/${KEYFACTOR_API_PATH}/CertificateStoreTypes" \
  -H "Authorization: Bearer ${KEYFACTOR_AUTH_TOKEN}" \
  -H "Content-Type: application/json" \
  -H "x-keyfactor-requested-with: APIClient" \
  -d '{
  "Name": "Azure Application Gateway Certificate Binding",
  "ShortName": "AppGwBin",
  "Capability": "AzureAppGwBin",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Remove": false,
    "Enrollment": false,
    "Discovery": true,
    "Inventory": false
  },
  "Properties": [
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "Description": "Application ID of the service principal, representing the identity used for managing the Application Gateway.",
      "Required": false
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Type": "Secret",
      "Description": "A Client Secret that the extension will use to authenticate with the Azure Resource Management API for managing Application Gateway certificates, OR the password that encrypts the private key in ClientCertificate",
      "Required": false
    },
    {
      "Name": "ClientCertificate",
      "DisplayName": "Client Certificate",
      "Type": "Secret",
      "Description": "The client certificate used to authenticate with Azure Resource Management API for managing Application Gateway certificates. See the [requirements](#client-certificate-or-client-secret) for more information.",
      "Required": false
    },
    {
      "Name": "AzureCloud",
      "DisplayName": "Azure Global Cloud Authority Host",
      "Type": "MultipleChoice",
      "DefaultValue": "public,china,government",
      "Description": "Specifies the Azure Cloud instance used by the organization.",
      "Required": false
    },
    {
      "Name": "ServerUseSsl",
      "DisplayName": "Use SSL",
      "Type": "Bool",
      "DefaultValue": "true",
      "Description": "Specifies whether SSL should be used for communication with the server. Set to 'true' to enable SSL, and 'false' to disable it.",
      "Required": true
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "PrivateKeyAllowed": "Required",
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required"
}'

