#!/bin/bash
# Store Type creation script using kfutil
# Generated by Doctool

set -e

echo "Creating store type: AzureAppGw"
kfutil store-types create AzureAppGw

echo "Creating store type: AppGwBin"
kfutil store-types create AppGwBin

